### Numpy Mastery Assignment
- Answer all questions
- Submission : 20th September 2022

1. Create a 1D array of numbers from 0 to 9

In [1]:
import numpy as np

In [2]:
arr_1_dm = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_1_dm

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 3x3 numpy of all True 

In [3]:
arr_3_dm = np.array([[True, True, True],[True, True, True], [True, True, True]])
arr_3_dm

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Create an array of numbers from 20 to 39

In [4]:
num_20_to_39 = np.arange(20, 40)
num_20_to_39

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39])

4. Replace all odd numbers in Q3 by -1

In [5]:
num_20_to_39[num_20_to_39 % 2 == 1] = -1 
num_20_to_39

array([20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1, 36,
       -1, 38, -1])

5. Create two arrays of length 10 and print out  common items in both arrays

In [6]:
arr_1 = np.array([10, 11, 23, 19, 56, 12, 88, 17, 33, 33])
arr_2 = np.array([5, 33, 16, 19, 22, 77, 65, 90, 15, 29])
common = np.intersect1d(arr_1, arr_2)
common

array([19, 33])

6.  Create a 5x5 identity matrix

In [7]:
mtx = np.eye(5)
mtx

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

7. In the code cell below define and print a set of arrays defined x, y and z. The array x should be take the form [10 12 9 2 20], y should have  101  values from  10  to  20  inclusive and z should be a  2×3  array of ones.

In [8]:
x = np.array([10, 12, 9, 2, 20])
y = np.arange(10, 21)
z = np.ones((2, 3))

print(x)
print(y)
print(z)

[10 12  9  2 20]
[10 11 12 13 14 15 16 17 18 19 20]
[[1. 1. 1.]
 [1. 1. 1.]]


8.Using the available Numpy functions on array x from problem  7 , find the average and the standard deviation of the value in this array. Redefine x as an array with all these values sorted in numerical order.

In [9]:
x_avg = np.average(x)
x_std = np.std(x)

print("Average", x_avg)
print("Std", x_std)

x = np.array([x_std, x_avg])
x

Average 10.6
Std 5.782732917920384


array([ 5.78273292, 10.6       ])

9. Create a 10x10 array with random values and find the minimum and maximum values

In [10]:
arr = np.random.randint(low=0, high=100, size=(10, 10))
print(arr)

xmin, xmax = arr.min(), arr.max()
print("Min:", xmin, "Max:", xmax)

[[24 22 65 38 10 38  1 49 53 55]
 [59 17 31 14 44 92 38 51 33 79]
 [ 0 89  0 16 95 90 69 21  4 88]
 [79 91 57 25 95 32 69 50 45 37]
 [74 70 92 34 45 37 89 44 21 43]
 [67 58 51 76 14 69 21 86 72  9]
 [70  1 40 24 81 72 30 26 79 92]
 [49 66 60 50 62  4 65 62 78 67]
 [79 44 71  8 14 11 86 31 54 51]
 [84 67 94 80 89  7 27 14 39 32]]
Min: 0 Max: 95


10. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
arr = np.arange(9).reshape(3, 3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


11.  Generates an array [[1 2 3] [4 5 6]]

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


12. Generates an array [0 2.5 5 7.5 10]

In [13]:
arr = np.array([0,2.5, 5, 7.5, 10])
print(arr)

[ 0.   2.5  5.   7.5 10. ]


13. Generates an 3x3 array of zeros

In [14]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


14. Create array from 0.1 to 10 with 12 elements, inclusively

In [15]:
arr = np.linspace(0.1, 10, 12)
print(arr)

[ 0.1  1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]


15. Create a matrix with seven columns and five rows of ten(10).

In [16]:
arr = np.full((5, 7), 10)
print(arr)

[[10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10]]


16. What is the difference between numpy and list?

In [17]:
# NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays
# List is an in-built data structure to store multiple items in a single variable.

17. Create a 1D array of ones consisting of  50  values. Change the values of the array so that the values alternate between ones and zeros ie  1,0,1,0,1,0,1,0,1...  ensuring that the starting value is  1 

In [18]:
arr = np.ones(50)
arr[0]=1
arr[1::2] = 0
arr

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1.,
       0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.,
       1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])

18. Generate a  10×10  matrix of zeros.
Make this matrix an identity matrix

In [19]:
arr = np.eye((10))
print(arr)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


19. Generate an array x to be a  10×10  array of zeros. Redefine its diagonal components (from left to right) to equal one

In [20]:
x = np.zeros((10,10))
np.fill_diagonal(x,1)
print(x)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


20. What is the dot products of this two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [21]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6], [7,8]])
c = np.dot(a,b)
c

array([[19, 22],
       [43, 50]])

21.  Multiply these two matrix [[1,2],[3,4]] and [[5,6],[7,8]]

In [22]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6], [7,8]])
c = a*b
c

array([[ 5, 12],
       [21, 32]])

22. Multiply this matrix  [[1,2],[3,4]] by a  scalar value of 5

In [23]:
scalar = 5
a = np.array([[1,2],[3,4]])
scalar * a

array([[ 5, 10],
       [15, 20]])

23. A = [[1,2],[3,4]] and B = transpose of A. Calculate AxB

In [24]:
A = np.array([[1,2],[3,4]])
B = np.transpose(A)
A*B

array([[ 1,  6],
       [ 6, 16]])

24. A= [[1,2],[3,4]] and B =  [[5,6],[7,8]]. Is A x B = B x A ? Show working

In [41]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
C = A*B
D = B*A

print(C)
print()
print(D)

show_working = C == D

show_working.astype(bool)

# C = D BECAUSE OF THE COMMUTATIVE PROPERTY OF MULTIPLICATION.

[[ 5 12]
 [21 32]]

[[ 5 12]
 [21 32]]


array([[ True,  True],
       [ True,  True]])

25. Creates an array [[0 1 2] [3 4 5]]
- Let A = first row of the matrix
- B = second row of the matrix
- C = second column of the Matrix
- D = first row, third column of the matrix
- print A , B , C, D

In [26]:
ARR = np.array([[0,1,2],[3,4,5]])
A = ARR[0,:]
B = ARR[1,:]
C = ARR[:,1]
D = ARR[0:,2]
print(A,B,C,D)

[0 1 2] [3 4 5] [1 4] [2 5]
